Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.box = "rancher-curso"
    master.vm.box = "centos7.2"
    master.vm.hostname = "rancher-curso"
    master.vm.provision :shell, path: "bootstrap.sh"
    master.vm.network "private_network", ip: "192.168.0.20"
    master.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
    master.vm.network "forwarded_port", guest: 10000, host: 10000, host_ip: "127.0.0.1"
    master.vm.synced_folder "./", "/rancher", owner: 'vagrant', group: 'vagrant', mount_options: ['dmode=775,fmode=775']
    master.vm.provider "virtualbox" do |v|
      v.memory = 3072
      v.cpus = 2
    end
  end

  config.vm.define "slave1" do |slave1|
    slave1.vm.box = "rancher-slave1"
    slave1.vm.box = "centos7.2"
    slave1.vm.hostname = "rancher-slave1"
    slave1.vm.provision :shell, path: "bootstrap.sh"
    slave1.vm.network "private_network", ip: "192.168.0.21"
    slave1.vm.network "forwarded_port", guest: 10005, host: 10005, host_ip: "127.0.0.1"
    slave1.vm.synced_folder "./", "/rancher", owner: 'vagrant', group: 'vagrant', mount_options: ['dmode=775,fmode=775']
    slave1.vm.provider "virtualbox" do |v|
      v.memory = 3072
      v.cpus = 2
    end
  end

  config.vm.define "slave2" do |slave2|
    slave2.vm.box = "rancher-slave2"
    slave2.vm.box = "centos7.2"
    slave2.vm.hostname = "rancher-slave2"
    slave2.vm.provision :shell, path: "bootstrap.sh"
    slave2.vm.network "private_network", ip: "192.168.0.22"
    slave2.vm.network "forwarded_port", guest: 10006, host: 10006, host_ip: "127.0.0.1"
    slave2.vm.synced_folder "./", "/rancher", owner: 'vagrant', group: 'vagrant', mount_options: ['dmode=775,fmode=775']
    slave2.vm.provider "virtualbox" do |v|
      v.memory = 3072
      v.cpus = 2
    end
  end
end
