Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.box = "rancher-curso"
    master.vm.box = "centos7.2"
    master.vm.hostname = "rancher-curso"
    master.vm.provision :shell, path: "bootstrap.sh"
    master.vm.network "private_network", ip: "192.168.0.20"
    master.vm.network "forwarded_port", guest: 10000, host: 10000, host_ip: "127.0.0.1"
    master.vm.synced_folder "./", "/rancher", owner: 'vagrant', group: 'vagrant', mount_options: ['dmode=775,fmode=775']
    master.vm.provider "virtualbox" do |v|
      v.memory = 3072
      v.cpus = 2
    end
  end

  config.vm.define "slave" do |slave|
    slave.vm.box = "rancher-slave1"
    slave.vm.box = "centos7.2"
    slave.vm.hostname = "rancher-slave1"
    slave.vm.provision :shell, path: "bootstrap.sh"
    slave.vm.network "private_network", ip: "192.168.0.21"
    slave.vm.network "forwarded_port", guest: 10001, host: 10001, host_ip: "127.0.0.1"
    slave.vm.synced_folder "./", "/rancher", owner: 'vagrant', group: 'vagrant', mount_options: ['dmode=775,fmode=775']
    slave.vm.provider "virtualbox" do |v|
      v.memory = 3072
      v.cpus = 2
    end
  end
end
